_target_: src.models.pet_model.PetModel

cfg:
  image_size: 224
  model:
    name: swin_tiny_patch4_window7_224
    output_dim: 1
  optimizer:
    name: optim.AdamW
    params:
      lr: 1e-5
  scheduler:
    name: optim.lr_scheduler.CosineAnnealingWarmRestarts
    params:
      T_0: 20
      eta_min: 1e-4
  loss: nn.BCEWithLogitsLoss